syntax on
let skip_defaults_vim = "true"
set nocompatible
colorscheme cleaver
set nowrap
set ruler
set autoindent
set expandtab
set shiftwidth=2
set softtabstop=2
set smartindent
filetype plugin indent on
set ignorecase
set smartcase
set undolevels=1000
set showmatch
set incsearch
set backspace=indent,eol,start
set hlsearch
set history=50
set wildmenu
"set relativenumber
iabbr gmt Greenwich Merridian Time
set listchars=tab:»·,trail:·,eol:¬
"set list

"" Fold comments by default.
"" Toggle with 'zi'.
"set fdm=expr
"set fde=getline(v:lnum)=~'^\\s#'?1:getline(prevnonblank(v:lnum))=~'^\\s#'?1:getline(nextnonblank(v:lnum))=~'^\\s*#'?1:0
